input OtpAuthInput {
    phone: String!
    otp: String!
    attempt: Int
}

input EmailPasswordAuthInput {
    email: String!
    password: String!
}

type Query {
    sendOtp (
        phone: String!
    ): String
}

type Mutation {
    logInOtp (
        auth: OtpAuthInput
    ): String

    logInEmail (
        auth: EmailPasswordAuthInput
    ): String

    logOut: String
}

schema {
    query: Query
    mutation: Mutation
}