directive @hasRole(
    oneOf: [String]
) on QUERY | FIELD | FIELD_DEFINITION

directive @cacheControl(
  maxAge: Int,
  scope: CacheControlScope
) on OBJECT | FIELD_DEFINITION

enum CacheControlScope {
  PUBLIC
  PRIVATE
}