directive @hasRole(
    anyOf: [String]
    allOf: [String]
) on QUERY | FIELD | FIELD_DEFINITION

directive @cache(
  maxAge: Int
  scope: CacheControlScope
  policy: CacheControlPolicy
) on OBJECT | FIELD_DEFINITION

enum CacheControlPolicy {
  PUBLIC
  PRIVATE
}

enum CacheControlScope {
  STATIC
  DYNAMIC
}